name: Smoothie Solutions
favicon: null
layout_spectrum: 0.22229286190122366
typography_spectrum: 0.1326098619028926
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#db443b'
    - '#e46a27'
    - '#8d8b8c'
    - '#cbcac8'
  brandStrength: 0.3125
  lightness: 0.9766815940383822
  saturation: 0.5
  rhythmicContrast: 0.3410391688812524
purpose: []
